USE DATABASE OLIST_DB;
USE SCHEMA GOLD;

-- ============================================================================
-- 1. DIMENSION VIEWS
-- ============================================================================

-- Geography Lookup Dimension View
CREATE OR REPLACE VIEW GOLD.DIM_GEOGRAPHY AS
SELECT 
    MD5(ZIP_CODE_PREFIX) AS GEOGRAPHY_KEY,
    ZIP_CODE_PREFIX,
    LATITUDE,
    LONGITUDE,
    CITY AS CITY,
    STATE AS STATE
FROM SILVER.GEOLOCATION_STG

UNION ALL

-- Unified fallback record to resolve referential gaps cleanly
SELECT 
    MD5('UNKNOWN') AS GEOGRAPHY_KEY, 
    'UNKNOWN' AS ZIP_CODE_PREFIX, 
    0.0 AS LATITUDE, 
    0.0 AS LONGITUDE, 
    'UNKNOWN' AS CITY, 
    'UNKNOWN' AS STATE;


-- Customer Attribute Dimension View
CREATE OR REPLACE VIEW GOLD.DIM_CUSTOMER AS
SELECT 
    MD5(c.CUSTOMER_ID) AS CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.CUSTOMER_UNIQUE_ID,
    COALESCE(g.GEOGRAPHY_KEY, MD5('UNKNOWN')) AS GEOGRAPHY_KEY
FROM SILVER.CUSTOMER_STG c
LEFT JOIN GOLD.DIM_GEOGRAPHY g ON c.ZIP_CODE_PREFIX = g.ZIP_CODE_PREFIX;


-- Seller Operational Dimension View
CREATE OR REPLACE VIEW GOLD.DIM_SELLER AS
SELECT 
    MD5(s.SELLER_ID) AS SELLER_KEY,
    s.SELLER_ID,
    COALESCE(g.GEOGRAPHY_KEY, MD5('UNKNOWN')) AS GEOGRAPHY_KEY
FROM SILVER.SELLER_STG s
LEFT JOIN GOLD.DIM_GEOGRAPHY g ON s.ZIP_CODE_PREFIX = g.ZIP_CODE_PREFIX;


-- Product Catalog Dimension View
CREATE OR REPLACE VIEW GOLD.DIM_PRODUCT AS
SELECT 
    MD5(PRODUCT_ID) AS PRODUCT_KEY,
    PRODUCT_ID,
    CATEGORY_NAME_ENGLISH,
    PRODUCT_WEIGHT_G,
	PRODUCT_LENGTH_CM,
	PRODUCT_HEIGHT_CM,
	PRODUCT_WIDTH_CM,
    (PRODUCT_LENGTH_CM * PRODUCT_HEIGHT_CM * PRODUCT_WIDTH_CM) AS PRODUCT_VOLUME_CM3
FROM SILVER.PRODUCT_STG

UNION ALL

-- Placeholder record for catalog dropouts
SELECT 
    MD5('UNKNOWN') AS PRODUCT_KEY, 
    'UNKNOWN' AS PRODUCT_ID, 
    'UNASSIGNED' AS CATEGORY_NAME_ENGLISH, 
    0 AS PRODUCT_WEIGHT_G, 
     0 AS PRODUCT_LENGTH_CM,
	 0 AS PRODUCT_HEIGHT_CM,
	 0 AS PRODUCT_WIDTH_CM,
    0 AS PRODUCT_VOLUME_CM3;

-- Time-Intelligence Calendar Dimension View
CREATE OR REPLACE VIEW GOLD.DIM_DATE AS
SELECT 
    REPLACE(DATEADD(day, SEQ4(), '2016-01-01')::DATE::VARCHAR, '-', '')::INT AS DATE_KEY,
    DATEADD(day, SEQ4(), '2016-01-01')::DATE AS FULL_DATE,
    YEAR(DATEADD(day, SEQ4(), '2016-01-01')::DATE) AS YEAR,
    QUARTER(DATEADD(day, SEQ4(), '2016-01-01')::DATE) AS QUARTER,
    MONTH(DATEADD(day, SEQ4(), '2016-01-01')::DATE) AS MONTH,
    MONTHNAME(DATEADD(day, SEQ4(), '2016-01-01')::DATE) AS MONTH_NAME,
    DAYOFWEEK(DATEADD(day, SEQ4(), '2016-01-01')::DATE) AS DAY_OF_WEEK,
    CASE 
        WHEN DAYOFWEEK(DATEADD(day, SEQ4(), '2016-01-01')::DATE) IN (0, 6) 
        THEN TRUE 
        ELSE FALSE 
    END AS IS_WEEKEND
FROM TABLE(GENERATOR(ROWCOUNT => 1200));

-- ============================================================================
-- 2. FACT VIEWS (Multi-Grain Fact Architecture)
-- ============================================================================

-- Core Order Line Items Fact View (Primary Operational Event Log)
CREATE OR REPLACE VIEW GOLD.FACT_ORDER_ITEMS AS
SELECT 
    MD5(CONCAT(oi.ORDER_ID, oi.ORDER_ITEM_ID)) AS ORDER_ITEM_KEY,
    oi.ORDER_ID,
    oi.ORDER_ITEM_ID,
    COALESCE(c.CUSTOMER_KEY, MD5('UNKNOWN')) AS CUSTOMER_KEY,
    COALESCE(s.SELLER_KEY, MD5('UNKNOWN')) AS SELLER_KEY,
    COALESCE(p.PRODUCT_KEY, MD5('UNKNOWN')) AS PRODUCT_KEY,
    
    -- Format timestamps to uniform INT keys matching your Calendar dimension
    COALESCE(REPLACE(o.ORDER_PURCHASE_TIMESTAMP::DATE::VARCHAR, '-', '')::INT, 19000101) AS PURCHASE_DATE_KEY,
    COALESCE(REPLACE(o.ORDER_APPROVED_AT::DATE::VARCHAR, '-', '')::INT, 19000101) AS APPROVED_DATE_KEY,
	COALESCE(REPLACE(o.ORDER_DELIVERED_CARRIER_DATE::DATE::VARCHAR, '-', '')::INT, 19000101) AS DELIVERED_CARRIER_DATE_KEY,
	COALESCE(REPLACE(o.ORDER_ESTIMATED_DELIVERY_DATE::DATE::VARCHAR, '-', '')::INT, 19000101) AS ESTIMATED_DELIVERY_DATE_KEY,	
    COALESCE(REPLACE(o.ORDER_DELIVERED_CUSTOMER_DATE::DATE::VARCHAR, '-', '')::INT, 19000101) AS DELIVERED_DATE_KEY,
    
    oi.PRICE,
    oi.FREIGHT_VALUE,
    
    -- Logistics Performance metrics
    DATEDIFF('day', o.ORDER_PURCHASE_TIMESTAMP, o.ORDER_DELIVERED_CUSTOMER_DATE) AS DELIVERY_DAYS_ACTUAL,
    DATEDIFF('day', o.ORDER_PURCHASE_TIMESTAMP, o.ORDER_ESTIMATED_DELIVERY_DATE) AS DELIVERY_DAYS_ESTIMATED,
    CASE 
        WHEN o.ORDER_DELIVERED_CUSTOMER_DATE > o.ORDER_ESTIMATED_DELIVERY_DATE THEN 1 
        ELSE 0 
    END AS IS_LATE,
    
    -- Integrated Haversine Formula calculating great-circle transit distance (km)
    COALESCE(
        2 * 6371.009 * ASIN(SQRT(
            POWER(SIN(RADIANS(c_geo.LATITUDE - s_geo.LATITUDE) / 2), 2) +
            COS(RADIANS(s_geo.LATITUDE)) * COS(RADIANS(c_geo.LATITUDE)) * 
            POWER(SIN(RADIANS(c_geo.LONGITUDE - s_geo.LONGITUDE) / 2), 2)
        )), 0.0
    ) AS AVG_DISTANCE_KM

FROM SILVER.ORDER_ITEM_STG oi
JOIN SILVER.ORDER_STG o ON oi.ORDER_ID = o.ORDER_ID
LEFT JOIN GOLD.DIM_CUSTOMER c ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN GOLD.DIM_SELLER s ON oi.SELLER_ID = s.SELLER_ID
LEFT JOIN GOLD.DIM_PRODUCT p ON oi.PRODUCT_ID = p.PRODUCT_ID

-- Spatial lookup maps to extract centroids
LEFT JOIN GOLD.DIM_GEOGRAPHY c_geo ON c.GEOGRAPHY_KEY = c_geo.GEOGRAPHY_KEY
LEFT JOIN GOLD.DIM_GEOGRAPHY s_geo ON s.GEOGRAPHY_KEY = s_geo.GEOGRAPHY_KEY
WHERE o.IS_CHRONOLOGICALLY_VALID = TRUE;


-- Transactional Payments Fact View (Isolated at the specific installment level)
CREATE OR REPLACE VIEW GOLD.FACT_PAYMENTS AS
SELECT 
    ORDER_ID, 
    PAYMENT_SEQUENTIAL, 
    PAYMENT_TYPE, 
    PAYMENT_INSTALLMENTS, 
    PAYMENT_VALUE
FROM SILVER.PAYMENT_STG;


-- Customer Experience Review Sentiment Fact View (Isolated at the specific evaluation level)
CREATE OR REPLACE VIEW GOLD.FACT_REVIEWS AS
SELECT 
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    COALESCE(REPLACE(REVIEW_CREATION_DATE::DATE::VARCHAR, '-', '')::INT, 19000101) AS REVIEW_DATE_KEY
FROM SILVER.REVIEW_STG;



